# Using Window Functions to perform deeper analytical tasks

In [1]:
import pandas as pd
import mysql.connector
import matplotlib.pyplot as plt
conn = mysql.connector.connect(host='127.0.0.1',user='root',password='*****',database='smartphones')

1. Select Smartphones along with average price of thier corresponding brands

In [14]:
q1 = "SELECT brand_name,model,price,ROUND(AVG(price) OVER (PARTITION BY brand_name),2)  AS 'Avg-Price' FROM sp"

In [18]:
pd.read_sql_query(q1,con=conn).sample(40)

C:\Users\itCare\AppData\Local\Temp\ipykernel_201100\4218380659.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query(q1,con=conn).sample(40)

    brand_name                                 model   price  Avg-Price
186   motorola                    Motorola Edge Plus   57999   21587.88
582      tecno                        Tecno Camon 19   14746   15054.81
669       vivo                           Vivo V20 SE   19000   21114.28
500    samsung  Samsung Galaxy A52 (8GB RAM + 128GB)   22494   29290.48
323       oppo               OPPO Reno 6 Pro Plus 5G   44990   25768.34
606      tecno                   Tecno Spark Go 2022    6249   15054.81
234    oneplus        OnePlus 10T (16GB RAM + 256GB)   55999   32177.43
464     royole                      Royole FlexPai 2  109999  129999.00
276       oppo                    OPPO Reno 9 Pro 5G   39999   25768.34
254       oppo                      OPPO Reno 10 Pro   42990   25768.34
645       vivo                           Vivo V21 5G   23994   21114.28
347       poco                               Poco F5   34990   18747.41
760     xiaomi                     Xiaomi Redmi K60E   25999   23958.32
75     infinix     Infinix Note 12 (6GB RAM + 128GB)   12999   14938.57
444     realme                            Realme C11    6490   18030.72
260       oppo                           OPPO A96 4G   17999   25768.34
617       vivo                           Vivo Y55 5G   20990   21114.28
360       poco                               Poco X5   14999   18747.41
590      tecno                          Tecno Pova 2   10999   15054.81
218    oneplus                  OnePlus Nord CE 3 5G   21999   32177.43
822     xiaomi                      Xiaomi Redmi 20X   10990   23958.32
446     realme                    Realme 10 Pro Plus   24999   18030.72
106       iqoo             iQOO 7 (12GB RAM + 256GB)   35990   30634.52
176   motorola             Motorola Moto Edge 30 Neo   31990   21587.88
533    samsung                   Samsung Galaxy A50s   15990   29290.48
482    samsung               Samsung Galaxy Z Flip 3   69999   29290.48
211    oneplus                    OnePlus Nord 2T 5G   28999   32177.43
525    samsung                 Samsung Galaxy A83 5G   39990   29290.48
295       oppo                           OPPO A57 4G   11990   25768.34
598      tecno                         Tecno Spark 9    8999   15054.81
782     xiaomi   Xiaomi Mi 11 Lite (8GB RAM + 128GB)   18699   23958.32
300       oppo                              OPPO A17   12499   25768.34
242    oneplus                     OnePlus Nord 4 5G   29999   32177.43
232    oneplus                         OnePlus 9 Pro   64800   32177.43
471    samsung                    Samsung Galaxy M04    8499   29290.48
201    nothing                  Nothing Phone 1 Lite   24990   31195.40
456     realme                      Realme GT Neo 4T   29999   18030.72
84     infinix               Infinix Note 12i (2022)    9999   14938.57
365       poco                              POCO C31    6499   18747.41
209    oneplus                       OnePlus Nord SE   19999   32177.43

2. Most Costliest Phone of each brand

In [46]:
q1='''WITH CTE AS 
(
    SELECT brand_name,model,price ,MAX(price) OVER (partition by brand_name)  AS max_price FROM sp
)
SELECT * FROM CTE WHERE price = max_price
'''

In [47]:
pd.read_sql_query(q1,con=conn)

C:\Users\itCare\AppData\Local\Temp\ipykernel_201100\2003521103.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query(q1,con=conn)

   brand_name                                   model   price  max_price
0       apple           Apple iPhone 13 Pro Max (1TB)  179900     179900
1        asus                 Asus ROG Phone 6 Pro 5G   89999      89999
2   blackview                    Blackview BV5200 Pro    8990       8990
3         blu                              BLU F91 5G   14990      14990
4        cola                              Cola Phone   14999      14999
5      doogee                            Doogee V Max   45999      45999
6      gionee                          Gionee M12 Pro    7499       7499
7      google                      Google Pixel 6 Pro   54300      54300
8       honor                             Honor 70 5G   39990      39990
9      huawei        Huawei Mate 50 RS Porsche Design  239999     239999
10      ikall                           iKall Z19 Pro    8099       8099
11    infinix                      Infinix Zero Ultra   36999      36999
12       iqoo              iQOO 11 (16GB RAM + 256GB)   64999      64999
13       itel                           itel Vision 3    6699       6699
14        jio                         Jio JioPhone 5G   11990      11990
15       lava                            Lava Agni 5G   17990      17990
16      leeco                            LeEco S1 Pro   10999      10999
17      leitz                           Leitz Phone 2  124990     124990
18     lenovo                     Lenovo Legion Pro 2   59999      59999
19       letv                        Letv Y1 Pro Plus    5999       5999
20         lg                              LG Wing 5G   54999      54999
21         lg                            LG Velvet 5G   54999      54999
22        lyf                             Lyf Earth 1    3990       3990
23   micromax         Micromax IN 2B (6GB RAM + 64GB)    7790       7790
24   motorola                 Motorola Edge 40 Pro 5G   59990      59990
25      nokia                               Nokia X30   41990      41990
26    nothing                         Nothing Phone 2   39990      39990
27      nubia              Nubia Red Magic 8 Pro Plus   60999      60999
28    oneplus                           OnePlus 9 Pro   64800      64800
29       oppo                             OPPO X 2021  134999     134999
30    oukitel                            Oukitel WP19   29990      29990
31       poco                           POCO F5 GT 5G   42999      42999
32     realme                      Realme GT 2 Pro 5G   49959      49959
33      redmi         Redmi Note 12 Pro Speed Edition   19999      19999
34     royole                     Royole FlexPai 3 5G  149999     149999
35    samsung                 Samsung Galaxy Z Fold 3  110999     110999
36      sharp                         Sharp Aquos R5G   59990      59990
37       sony                     Sony Xperia 5 IV 5G   82199      82199
38        tcl                               TCL Ion X    8990       8990
39      tecno                    Tecno Phantom X2 Pro   49999      49999
40      vertu                   Vertu Signature Touch  650000     650000
41       vivo          Vivo X80 5G (12GB RAM + 256GB)   59999      59999
42     xiaomi  Xiaomi Redmi K20 Pro Signature Edition  480000     480000
43        zte                    ZTE Axon 40 Ultra 5G   61990      61990

3. Top 10  Phones Based on  Price

In [74]:
q3 = "SELECT model,price,rating ,RANK() OVER (ORDER BY price DESC) AS rank_ FROM sp"

In [75]:
pd.read_sql_query(q3,con=conn).head(10)

C:\Users\itCare\AppData\Local\Temp\ipykernel_201100\3027341769.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query(q3,con=conn).head(10)

                                    model   price  rating  rank_
0                   Vertu Signature Touch  650000    62.0      1
1  Xiaomi Redmi K20 Pro Signature Edition  480000    88.0      2
2        Huawei Mate 50 RS Porsche Design  239999    81.0      3
3           Apple iPhone 13 Pro Max (1TB)  179900    86.0      4
4                        Huawei Mate Xs 2  162990    89.0      5
5                     Royole FlexPai 3 5G  149999    87.0      6
6               Apple iPhone 13 Pro (1TB)  147900    84.0      7
7         Apple iPhone 13 Pro Max (256GB)  139900    84.0      8
8                             OPPO X 2021  134999    86.0      9
9                 Apple iPhone 13 Pro Max  129900    84.0     10

4. Top Rated Phone for each brand

In [78]:
q4 = '''WITH CTE AS (SELECT brand_name,model,rating , RANK() OVER(PARTITION BY brand_name ORDER BY rating) AS rank_ FROM sp) SELECT * FROM CTE WHERE rank_ = 1'''

In [79]:
pd.read_sql_query(q4,con=conn)

C:\Users\itCare\AppData\Local\Temp\ipykernel_201100\1640408611.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query(q4,con=conn)

   brand_name                        model  rating  rank_
0       apple               Apple iPhone 9    61.0      1
1        asus               Asus ZenFone 9    86.0      1
2        asus             Asus ROG Phone 6    86.0      1
3   blackview         Blackview BV5200 Pro    67.0      1
4         blu                   BLU F91 5G    85.0      1
5        cola                   Cola Phone    74.0      1
6      doogee                   Doogee S99    84.0      1
7      gionee               Gionee M12 Pro    67.0      1
8      google           Google Pixel 3a XL    67.0      1
9       honor                Honor Play 30    68.0      1
10     huawei              Huawei Honor 9N    66.0      1
11      ikall                iKall Z19 Pro    60.0      1
12    infinix              Infinix Smart 6    60.0      1
13       iqoo              iQOO Z6 Lite 5G    75.0      1
14       itel                itel Vision 3    61.0      1
15        jio              Jio JioPhone 5G    64.0      1
16       lava               Lava Blaze NXT    66.0      1
17      leeco                 LeEco S1 Pro    65.0      1
18      leitz                Leitz Phone 2    89.0      1
19     lenovo            Lenovo Legion Y90    87.0      1
20       letv             Letv Y1 Pro Plus    60.0      1
21         lg                 LG Velvet 5G    85.0      1
22        lyf                  Lyf Earth 1    60.0      1
23   micromax               Micromax IN 2C    60.0      1
24   motorola            Motorola Moto E13    65.0      1
25   motorola           Motorola Moto E32s    65.0      1
26      nokia                    Nokia C31    62.0      1
27    nothing         Nothing Phone 1 Lite    80.0      1
28      nubia                    Nubia Z50    82.0      1
29    oneplus            OnePlus Nord N100    68.0      1
30       oppo                     OPPO A73    62.0      1
31       oppo                    OPPO A17K    62.0      1
32    oukitel                  Oukitel WP9    72.0      1
33       poco    Poco C50 (3GB RAM + 32GB)    61.0      1
34     realme  Realme C30 (3GB RAM + 32GB)    60.0      1
35      redmi                    Redmi 12C    70.0      1
36     royole             Royole FlexPai 2    87.0      1
37     royole          Royole FlexPai 3 5G    87.0      1
38    samsung           Samsung Galaxy A11    63.0      1
39      sharp              Sharp Aquos R5G    88.0      1
40       sony            Sony Xperia L5 5G    73.0      1
41        tcl                    TCL Ion X    60.0      1
42      tecno          Tecno Spark Go 2022    61.0      1
43      vertu        Vertu Signature Touch    62.0      1
44       vivo                    Vivo Y01A    60.0      1
45     xiaomi         Xiaomi Redmi A1 Plus    60.0      1
46        zte                 ZTE Axon 30S    82.0      1